<?php
require_once __DIR__ . '/security.php';
require_once __DIR__ . '/db.php';
require_admin();
function legacy_json_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function legacy_json_date($v,$fallback=null){$v=trim((string)$v);if($v==='')return $fallback;try{$d=new DateTime($v);$d->setTimezone(new DateTimeZone('Asia/Kolkata'));return $d->format('Y-m-d');}catch(Throwable $e){return preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)?$v:$fallback;}}
function legacy_json_datetime($date,$time=''){ $date=legacy_json_date($date);$time=trim((string)$time);if(!$date||!preg_match('/^\d{1,2}:\d{2}(?::\d{2})?$/',$time))return null;$p=explode(':',$time);return sprintf('%s %02d:%02d:%02d',$date,(int)$p[0],(int)$p[1],(int)($p[2]??0)); }
function legacy_json_shift($s,$p=''){ $s=strtolower(trim((string)$s));$p=strtolower(trim((string)$p));$r=strpos($p,'reserved')!==false;if(strpos($s,'morning')!==false)return $r?'Morning Shift Reserved':'Morning Shift';if(strpos($s,'evening')!==false)return $r?'Evening Shift Reserved':'Evening Shift';return $r?'Full Day Reserved':'Full Day'; }
function legacy_json_plan_duration($from,$to,$cat=''){ $c=trim((string)$cat);if(in_array($c,['1','1 Month'],true))return '1 Month';if(in_array($c,['3','3 Months'],true))return '3 Months';if(in_array($c,['6','6 Months'],true))return '6 Months';$a=legacy_json_date($from);$b=legacy_json_date($to);if($a&&$b){$d=(new DateTime($a))->diff(new DateTime($b))->days+1;if($d>=175)return '6 Months';if($d>=80)return '3 Months';if($d>=20&&$d<=45)return '1 Month';}return 'Custom'; }
function legacy_json_mode($v){$v=trim((string)$v);foreach(['Cash','UPI','Online','Bank','Card','Other'] as $x)if(strcasecmp($x,$v)===0)return $x;return $v===''?'Cash':'Other';}
function legacy_json_receipt($base,&$seen){$base=preg_replace('/[^A-Za-z0-9_-]/','-',(string)$base);$base=substr($base?:'OLD-FEE',0,45);$c=$base;$i=2;while(isset($seen[$c])){$s='-'.$i++;$c=substr($base,0,50-strlen($s)).$s;}$seen[$c]=true;return $c;}
function legacy_json_out($ok,$msg,$extra=[]){echo '<div class="msg '.($ok?'ok':'err').'">'.legacy_json_h($msg).'</div>';if($extra){echo '<div class="stats">';foreach($extra as $k=>$v)echo '<div><b>'.legacy_json_h($v).'</b><span>'.legacy_json_h($k).'</span></div>';echo '</div>';}}
$csrf=function_exists('csrf_token')?csrf_token():'';$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_state_change();require_csrf();
 if(!isset($_FILES['legacy_json'])||$_FILES['legacy_json']['error']!==UPLOAD_ERR_OK)$result=['ok'=>false,'message'=>'Please select the old AR Library JSON backup file.'];
 else{$f=$_FILES['legacy_json'];if((int)$f['size']>20*1024*1024)$result=['ok'=>false,'message'=>'JSON backup must be 20 MB or smaller.'];else{$raw=@file_get_contents($f['tmp_name']);$data=$raw===false?null:json_decode($raw,true);
  if(!is_array($data))$result=['ok'=>false,'message'=>'The selected file is not valid JSON.'];
  elseif(($data['_meta']['app']??'')!=='AR Library')$result=['ok'=>false,'message'=>'This does not look like an AR Library legacy backup.'];
  elseif(!is_array($data['members']??null)||!is_array($data['feeRecords']??null))$result=['ok'=>false,'message'=>'Required legacy sections (members/feeRecords) are missing.'];
  else{$em=0;$ep=0;$r=$conn->query('SELECT COUNT(*) AS c FROM members');if($r)$em=(int)($r->fetch_assoc()['c']??0);$r=$conn->query('SELECT COUNT(*) AS c FROM payments');if($r)$ep=(int)($r->fetch_assoc()['c']??0);
   if($em>0||$ep>0)$result=['ok'=>false,'message'=>'Import stopped because current member/payment data already exists. Use Fresh Reset first, then run this one-time legacy import.'];
   else{$counts=['Members imported'=>0,'Fee payments imported'=>0,'Pending dues imported'=>0,'Attendance imported'=>0,'Seats imported'=>0,'Lockers imported'=>0,'Expenses imported'=>0,'Enquiries imported'=>0,'Settings imported'=>0];$map=[];$seen=[];
    $conn->query('SET FOREIGN_KEY_CHECKS=0');$conn->begin_transaction();
    try{
     foreach(($data['feeStructure']??[]) as $f2){$p=strtolower(trim((string)($f2['plan']??'')));$a=(float)($f2['amount']??0);if($a<=0)continue;$full=strpos($p,'full day')!==false;$res=strpos($p,'reserved')!==false;$k=$full?($res?'full_reserved_one':'full_day_one'):($res?'half_reserved_one':'half_day_one');$s=$conn->prepare('INSERT INTO fee_settings(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value');if(!$s)throw new RuntimeException('Could not prepare fee settings import.');$s->bind_param('sd',$k,$a);if(!$s->execute()){$s->close();throw new RuntimeException('Could not import fee settings.');}$s->close();}
     $settings=[];$lib=$data['appSettings']['library']??[];if(isset($lib['name']))$settings['library_name']=(string)$lib['name'];if(isset($lib['phone']))$settings['phone']=(string)$lib['phone'];if(isset($lib['addr']))$settings['address']=(string)$lib['addr'];$sh=$data['appSettings']['shifts']??[];if(isset($sh['morningStart']))$settings['opening_time']=(string)$sh['morningStart'];if(isset($sh['eveningEnd']))$settings['closing_time']=(string)$sh['eveningEnd'];$seats=$data['appSettings']['seats']['total']??null;$locks=$data['lockerCount']['total']??($data['appSettings']['lockers']['total']??null);if($seats!==null)$settings['total_seats']=(string)(int)$seats;if($locks!==null)$settings['total_lockers']=(string)(int)$locks;
     foreach($settings as $k=>$v){$s=$conn->prepare('INSERT INTO library_settings(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value');if(!$s)throw new RuntimeException('Could not prepare library settings import.');$s->bind_param('ss',$k,$v);if(!$s->execute()){$s->close();throw new RuntimeException('Could not import library settings.');}$s->close();$counts['Settings imported']++;}
     foreach($data['members'] as $m){$old=trim((string)($m['id']??''));$code=$old;$name=trim((string)($m['name']??'Member'));if($code===''||$name==='')continue;$join=legacy_json_date($m['from']??'',date('Y-m-d'));$valid=legacy_json_date($m['to']??'',null);$dob=legacy_json_date($m['dob']??'',null);$dur=legacy_json_plan_duration($m['from']??'',$m['to']??'',$m['category']??'');$shift=legacy_json_shift($m['shift']??'',$m['plan']??'');$status=strtolower(trim((string)($m['feeStatus']??'')))==='expired'?'Expired':'Active';$phone=trim((string)($m['phone']??''));$addr=trim((string)($m['addr']??''));$created=legacy_json_date($m['createdAt']??'',$join);$email='';$s=$conn->prepare('INSERT INTO members(member_id,name,phone,email,membership_plan,shift,joining_date,date_of_birth,validity_date,address,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare member import.');$s->bind_param('ssssssssssss',$code,$name,$phone,$email,$dur,$shift,$join,$dob,$valid,$addr,$status,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Member '.$code.' failed: '.$e);}$id=(int)$s->insert_id;$s->close();$map[$old]=['id'=>$id,'code'=>$code,'shift'=>$shift,'plan'=>(string)($m['plan']??'')];$guardian=trim((string)($m['guardian']??''));if($guardian!==''){$key='member_father_'.$id;$s=$conn->prepare('INSERT INTO library_settings(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value');if($s){$s->bind_param('ss',$key,$guardian);$s->execute();$s->close();}}$counts['Members imported']++;}
     foreach($data['feeRecords'] as $fr){$old=trim((string)($fr['memberId']??''));if(!isset($map[$old]))continue;$m=$map[$old];$date=legacy_json_date($fr['date']??'',date('Y-m-d'));$created=legacy_json_date($fr['createdAt']??'',$date);$amount=max(0,(float)($fr['amount']??0));$paid=max(0,(float)($fr['paidAmount']??0));$due=max(0,(float)($fr['dueAmount']??0));if($paid<=0&&$due<=0&&$amount>0)$paid=$amount;$mode=legacy_json_mode($fr['mode']??'Cash');$receipt=legacy_json_receipt($fr['id']??'OLD-FEE',$seen);$plan=(string)($fr['plan']??'');$notes=trim((string)($fr['notes']??''));
      if($paid>0){$type=$due>0?'Split':'Full';$extra=0.0;$s=$conn->prepare('INSERT INTO payments(receipt_no,member_id,member_code,amount,fee_amount,additional_charges,payment_type,payment_date,payment_method,plan,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare payment import.');$s->bind_param('sisdddssssss',$receipt,$m['id'],$m['code'],$paid,$paid,$extra,$type,$date,$mode,$plan,$notes,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Payment '.$receipt.' failed: '.$e);}$s->close();$st='Paid';$s=$conn->prepare('INSERT INTO member_fees(member_id,receipt_no,amount,payment_date,due_date,payment_method,status,remarks,created_at) VALUES(?,?,?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare paid fee import.');$s->bind_param('isdssssss',$m['id'],$receipt,$paid,$date,$date,$mode,$st,$notes,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Paid fee history failed: '.$e);}$s->close();$counts['Fee payments imported']++;}
      if($due>0){$dr=$receipt.'-D';$st='Pending';$rem='Imported legacy pending balance'.($notes!==''?': '.$notes:'');$s=$conn->prepare('INSERT INTO member_fees(member_id,receipt_no,amount,payment_date,due_date,payment_method,status,remarks,created_at) VALUES(?,?,?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare pending fee import.');$s->bind_param('isdssssss',$m['id'],$dr,$due,$date,$date,$mode,$st,$rem,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Pending fee history failed: '.$e);}$s->close();$counts['Pending dues imported']++;}
     }
     foreach(($data['attendance']??[]) as $a){$old=trim((string)($a['memberId']??''));if(!isset($map[$old]))continue;$date=legacy_json_date($a['date']??'',null);if(!$date)continue;$in=legacy_json_datetime($a['date']??'',$a['in']??'');$out=legacy_json_datetime($a['date']??'',$a['out']??'');$st=$out?'Closed':'Open';$rem=trim((string)($a['shift']??''));$created=legacy_json_date($a['createdAt']??'',$date);$s=$conn->prepare('INSERT INTO attendance(member_id,attendance_date,check_in,check_out,status,remarks,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(member_id,attendance_date) DO UPDATE SET check_in=excluded.check_in,check_out=excluded.check_out,status=excluded.status,remarks=excluded.remarks');if(!$s)throw new RuntimeException('Could not prepare attendance import.');$s->bind_param('isssssss',$map[$old]['id'],$date,$in,$out,$st,$rem,$created,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Attendance import failed: '.$e);}$s->close();$counts['Attendance imported']++;}
     foreach($data['members'] as $m){$old=trim((string)($m['id']??''));$seat=trim((string)($m['seat']??''));if($seat===''||!isset($map[$old]))continue;$start=legacy_json_date($m['from']??'',date('Y-m-d'));$end=legacy_json_date($m['to']??'',null);$st='Assigned';$rem='Imported from legacy backup';$created=legacy_json_date($m['createdAt']??'',$start);$s=$conn->prepare('INSERT INTO member_seats(member_id,seat_no,shift,start_date,end_date,status,remarks,created_at) VALUES(?,?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare seat import.');$s->bind_param('isssssss',$map[$old]['id'],$seat,$map[$old]['shift'],$start,$end,$st,$rem,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Seat import failed: '.$e);}$s->close();$counts['Seats imported']++;}
     foreach(($data['lockerData']??[]) as $l){$old=trim((string)($l['memberId']??''));if(!isset($map[$old]))continue;$locker=trim((string)($l['no']??''));if($locker==='')continue;$start=legacy_json_date($l['from']??'',date('Y-m-d'));$end=legacy_json_date($l['to']??'',null);$st='Assigned';$rem=trim((string)($l['notes']??''));$created=legacy_json_date($l['assignedAt']??'',$start);$s=$conn->prepare('INSERT INTO lockers(locker_no,member_id,start_date,end_date,status,remarks,created_at) VALUES(?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare locker import.');$s->bind_param('sisssss',$locker,$map[$old]['id'],$start,$end,$st,$rem,$created);if(!$s->execute()){$e=$s->error;$s->close();throw new RuntimeException('Locker import failed: '.$e);}$s->close();$counts['Lockers imported']++;}
     foreach(($data['expenses']??[]) as $e2){$date=legacy_json_date($e2['date']??'',date('Y-m-d'));$cat=trim((string)($e2['cat']??'Other'))?:'Other';$desc=trim((string)($e2['desc']??''));$amt=max(0,(float)($e2['amount']??0));if($amt<=0)continue;$mode=legacy_json_mode($e2['mode']??'Cash');$notes=trim((string)($e2['notes']??''));$created=legacy_json_date($e2['createdAt']??'',$date);$vendor='';$s=$conn->prepare('INSERT INTO expenses(expense_date,category,description,amount,payment_method,vendor,notes,created_at) VALUES(?,?,?,?,?,?,?,?)');if(!$s)throw new RuntimeException('Could not prepare expense import.');$s->bind_param('sssdssss',$date,$cat,$desc,$amt,$mode,$vendor,$notes,$created);if(!$s->execute()){$e3=$s->error;$s->close();throw new RuntimeException('Expense import failed: '.$e3);}$s->close();$counts['Expenses imported']++;}
     foreach(($data['enquiries']??[]) as $e2){$name=trim((string)($e2['name']??''));if($name==='')continue;$phone=trim((string)($e2['phone']??''));$req=trim((string)($e2['cls']??''));$shift=trim((string)($e2['shift']??''));if($shift!=='')$req=trim($req.($req!==''?' | ':'').'Shift: '.$shift);$follow=legacy_json_date($e2['date']??'',null);$sr=strtolower(trim((string)($e2['status']??'Open')));$st=$sr==='converted'?'Converted':($sr==='closed'?'Closed':'Open');$notes=trim((string)($e2['notes']??''));$addr=trim((string)($e2['address']??''));if($addr!=='')$notes=trim($notes.($notes!==''?"\n":'').'Address: '.$addr);$created=legacy_json_date($e2['createdAt']??'',$follow?:date('Y-m-d'));$s=$conn->prepare('INSERT INTO enquiries(name,phone,requirement,follow_up,status,notes,created_at) VALUES(?,?,?,NULLIF(?,""),?,?,?)');if(!$s)throw new RuntimeException('Could not prepare enquiry import.');$s->bind_param('sssssss',$name,$phone,$req,$follow,$st,$notes,$created);if(!$s->execute()){$e3=$s->error;$s->close();throw new RuntimeException('Enquiry import failed: '.$e3);}$s->close();$counts['Enquiries imported']++;}
     $conn->commit();$conn->query('SET FOREIGN_KEY_CHECKS=1');$result=['ok'=>true,'message'=>'Legacy JSON import completed successfully. The current Admin account/password was kept unchanged.','counts'=>$counts];
    }catch(Throwable $e){try{$conn->rollback();}catch(Throwable $ignored){}$conn->query('SET FOREIGN_KEY_CHECKS=1');$result=['ok'=>false,'message'=>'Import failed and was rolled back: '.$e->getMessage()];}
   }
  }
 }}
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AR Library · Legacy JSON Import</title><style>body{margin:0;background:#f5f7fb;color:#172033;font-family:Arial,sans-serif}.wrap{max-width:760px;margin:40px auto;padding:20px}.card{background:#fff;border:1px solid #e2e7f0;border-radius:16px;padding:24px;box-shadow:0 8px 30px rgba(20,30,50,.06)}h1{margin:0 0 8px}.muted{color:#667085;line-height:1.55}.warn{background:#fff7e8;border:1px solid #f3cf8c;border-radius:12px;padding:14px;margin:18px 0}.msg{border-radius:12px;padding:14px;margin:18px 0;font-weight:700}.msg.ok{background:#eaf8ef;color:#176b3a;border:1px solid #a9ddbc}.msg.err{background:#fff0f0;color:#a11f1f;border:1px solid #efb1b1}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:15px}.stats div{background:#f6f8fc;border-radius:12px;padding:13px}.stats b{display:block;font-size:20px}.stats span{color:#667085;font-size:12px}.btn{display:inline-block;border:0;border-radius:10px;background:#173b72;color:#fff;padding:12px 18px;font-weight:800;cursor:pointer}.file{display:block;width:100%;padding:12px;border:1px solid #d6dce8;border-radius:10px;margin:12px 0 16px;box-sizing:border-box}a{color:#173b72;text-decoration:none}</style></head><body><div class="wrap"><div class="card"><h1>Legacy JSON Import</h1><p class="muted">One-time migration from the old AR Library JSON backup to the current database.</p><div class="warn"><b>Important:</b> This importer does not delete existing data. It stops if members or payment records already exist. Use Fresh Reset first for a clean migration.</div><?php if($result)legacy_json_out($result['ok'],$result['message'],$result['counts']??[]); ?><?php if(!$result||!$result['ok']): ?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=legacy_json_h($csrf)?>"><label><b>Old JSON backup</b></label><input class="file" type="file" name="legacy_json" accept="application/json,.json" required><button class="btn" type="submit" onclick="return confirm('Old JSON data current database me import karna hai? Current Admin account/password unchanged rahega.')">Import Legacy JSON</button></form><?php endif; ?><p class="muted" style="margin-top:20px">After a successful one-time import, this file can be removed from the server.</p><p><a href="index.php">← Back to AR Library</a></p></div></div></body></html>
