<?php
require_once __DIR__ . '/security.php';
require_once __DIR__ . '/db.php';
require_permission('attendance_qr');
if (!isset($_SESSION["staff_id"])) { header("Location: index.php"); exit; }
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AR Library - Permanent Attendance QR</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
<style>*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Arial,sans-serif;background:linear-gradient(135deg,#eef4ff,#fff);display:flex;justify-content:center;align-items:center;padding:20px}.card{width:100%;max-width:650px;background:#fff;border-radius:24px;padding:28px;text-align:center;box-shadow:0 15px 50px rgba(0,0,0,.12)}.brand{font-size:30px;font-weight:900;color:#26365b}.sub{color:#777;font-size:13px;font-weight:700;letter-spacing:1px;margin:5px 0 18px}h1{font-size:25px;margin:10px}.ok{display:inline-block;padding:8px 12px;border-radius:999px;background:#e9f8ef;color:#15803d;font-weight:800;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0}.item{background:#f7f8fb;border-radius:12px;padding:12px;text-align:left}.item b{display:block;font-size:11px;color:#667085;margin-bottom:4px}.item span{font-weight:800;color:#26365b}#qrcode{width:320px;height:320px;margin:20px auto;display:flex;align-items:center;justify-content:center;background:#fff}.note{color:#667085;line-height:1.5;font-size:13px}.btn{display:inline-block;margin-top:15px;padding:12px 20px;border-radius:10px;text-decoration:none;background:#26365b;color:#fff;font-weight:800}@media(max-width:520px){.grid{grid-template-columns:1fr}#qrcode{width:270px;height:270px}}
@media print{body{background:#fff;padding:0}.card{box-shadow:none;max-width:none;border:0}.btn{display:none}.note{display:block}#qrcode{margin:20px auto}}
</style></head><body><div class="card"><img src="assets/ar-library-logo.webp" alt="AR Library logo" style="width:90px;height:90px;object-fit:contain;border-radius:16px;margin-bottom:6px"><div class="brand">AR LIBRARY</div><div class="sub">SILENT SELF STUDY ZONE</div><h1>📱 Permanent Attendance QR</h1><div class="ok">🔒 Permanent QR — इसे एक बार print करके हमेशा use करें</div><div id="qrcode"></div><div class="grid"><div class="item"><b>LATITUDE</b><span id="lat">—</span></div><div class="item"><b>LONGITUDE</b><span id="lng">—</span></div><div class="item"><b>ALLOWED RADIUS</b><span id="radius">—</span></div><div class="item"><b>VERIFICATION</b><span>GPS + Member Login</span></div><div class="item"><b>QR STATUS</b><span>Permanent — No Expiry</span></div></div><p class="note">Member must be logged in and physically within the configured radius. Location distance is verified on the PHP server.</p><button class="btn" type="button" onclick="window.print()">🖨️ Print QR</button> <a class="btn" href="index.php">← Back to Dashboard</a></div>
<script>
async function loadAttendanceQR(){try{const r=await fetch('qr_generate.php',{cache:'no-store'});const d=await r.json();if(!d.success)throw new Error(d.message||'Failed');document.getElementById('lat').textContent=d.latitude;document.getElementById('lng').textContent=d.longitude;document.getElementById('radius').textContent=d.radius_meters+' meters';const box=document.getElementById('qrcode');box.innerHTML='';new QRCode(box,{text:d.qr_url,width:300,height:300,correctLevel:QRCode.CorrectLevel.H});}catch(e){document.getElementById('qrcode').textContent=e.message;}}
loadAttendanceQR();
</script></body></html>
