(function(){
'use strict';
const $=id=>document.getElementById(id);
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content||'';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);
const form=(o={})=>{const f=new FormData();Object.entries(o).forEach(([k,v])=>f.append(k,v??''));return f};
async function req(url,opts={}){const method=(opts.method||'GET').toUpperCase();const headers=new Headers(opts.headers||{});if(method!=='GET')headers.set('X-CSRF-Token',csrf());const r=await fetch(url,{...opts,method,headers,credentials:'same-origin',cache:'no-store'});const ct=r.headers.get('content-type')||'';if(ct.includes('application/json')){let d;try{d=await r.json()}catch(e){throw Error('Server returned invalid JSON (HTTP '+r.status+').')}if(r.status===401){location.href='index.php';throw Error(d.message||'Please login again.')}if(!r.ok||d.success===false)throw Error(d.message||('Request failed (HTTP '+r.status+').'));return d;}const text=await r.text();if(!r.ok)throw Error('Request failed (HTTP '+r.status+'). '+text.slice(0,180));throw Error('Server returned an unexpected response.');}
const api=(a,o={})=>req('admin_api.php?action='+a,o);
const payApi=(a,o={})=>req('payments_api.php?action='+encodeURIComponent(a),o);
function card(html,cls='card'){return '<div class="'+cls+'" style="background:#fff;border-radius:14px;padding:20px;box-shadow:0 5px 22px rgba(20,40,80,.06)">'+html+'</div>'}
function table(headers,rows){return '<div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr>'+headers.map(h=>'<th style="text-align:left;padding:10px;border-bottom:1px solid #e8edf5;white-space:nowrap">'+h+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>'}
function input(label,name,value='',type='text'){return '<label style="display:block;font-weight:700;font-size:13px;margin-bottom:12px">'+label+'<input id="'+esc(name)+'" name="'+esc(name)+'" type="'+esc(type)+'" value="'+esc(value)+'" style="width:100%;margin-top:6px;padding:10px 12px;border:1px solid #d8dfeb;border-radius:9px;box-sizing:border-box"></label>'}
function select(label,name,opts,value=''){return '<label style="display:block;font-weight:700;font-size:13px;margin-bottom:12px">'+label+'<select name="'+name+'" style="width:100%;margin-top:6px;padding:10px 12px;border:1px solid #d8dfeb;border-radius:9px;background:#fff">'+opts.map(x=>'<option value="'+esc(x[0])+'" '+(x[0]===value?'selected':'')+'>'+esc(x[1])+'</option>').join('')+'</select></label>'}
function buttons(){return '<button type="submit" class="btn primary" style="padding:10px 16px">Save</button>'}
function setTitle(t){$('pageTitle').textContent=t;$('dateText').textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});}
function active(p){document.querySelectorAll('.nav-item[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));}
function loading(){ $('content').innerHTML=card('<div style="font-weight:800">Loading…</div>'); }
function fail(e){const msg=e&&e.message?e.message:String(e||'Unknown error');$('content').innerHTML=card('<h2>Unable to load</h2><p>'+esc(msg)+'</p><button class="btn primary" onclick="loadPage(\'dashboard\')">Back to Dashboard</button>');}

window.openLogin=function(role){role=String(role||'staff').toLowerCase()==='admin'?'admin':'staff';$('selectedRole').value=role;$('loginRoleTitle').textContent=role==='admin'?'ADMIN LOGIN':'STAFF LOGIN';$('loginRoleIcon').textContent=role==='admin'?'🔐':'👤';$('loginDemo').textContent=role==='admin'?'Admin login — use your Admin Staff ID and password.':'Staff login — use your Staff ID and password.';$('roleScreen').classList.add('hidden');$('loginScreen').classList.remove('hidden');setTimeout(()=>$('staffId').focus(),30)};
window.showRole=function(){$('loginScreen').classList.add('hidden');$('roleScreen').classList.remove('hidden');$('staffId').value='';$('password').value='';};
function loginMsg(t,ok=false){let e=$('loginMessage');if(!e){e=document.createElement('p');e.id='loginMessage';e.style.cssText='margin:12px 0;text-align:center;font-weight:800';$('loginScreen').querySelector('.login-card').appendChild(e)}e.textContent=t;e.style.color=ok?'#198754':'#c03955'}
window.login=async function(){const staffId=$('staffId').value.trim(),password=$('password').value,role=$('selectedRole').value;if(!staffId||!password)return loginMsg('Staff ID and password are required.');const bs=$('loginScreen').querySelectorAll('button');bs.forEach(b=>b.disabled=true);loginMsg('Signing in…',true);try{const d=await req('login.php',{method:'POST',body:form({staff_id:staffId,password,role})});if(String(d.role).toLowerCase()!==role)throw Error('Selected role does not match this account.');$('loginScreen').classList.add('hidden');$('roleScreen').classList.add('hidden');$('app').classList.remove('hidden');location.reload();}catch(e){loginMsg(e.message)}finally{bs.forEach(b=>b.disabled=false)}};
window.logout=()=>location.href='logout.php';

function dashboard(d){
 const s=d&&d.stats?d.stats:{};
 const trend=Array.isArray(d&&d.trend)?d.trend:[];
 const activities=Array.isArray(d&&d.activities)?d.activities:[];
 const birthdays=Array.isArray(d&&d.birthdays)?d.birthdays:[];
 const expiry=Array.isArray(d&&d.expiry)?d.expiry:[];
 const role=(document.body.dataset.role||'staff').toLowerCase();
 const name=(document.getElementById('userName')?.textContent||'').trim() || (role==='admin'?'Administrator':'Team Member');
 const occ=s.total_seats?Math.round((Number(s.occupied||0)/Number(s.total_seats||1))*100):0;
 const lockerOcc=s.total_lockers?Math.round((Number(s.occupied_lockers||0)/Number(s.total_lockers||1))*100):0;
 const maxTrend=Math.max(1,...trend.map(x=>Math.max(Number(x.collection||0),Number(x.expenses||0))));
 const shortDay=x=>{const dt=new Date(String(x)+'T00:00:00');return isNaN(dt)?esc(x):dt.toLocaleDateString('en-IN',{day:'2-digit',month:'short'});};
 const stat=(icon,label,value,note,cls)=>'<div class="dash-kpi '+cls+'"><div class="kpi-icon">'+icon+'</div><div class="kpi-copy"><span>'+label+'</span><strong>'+esc(value)+'</strong><small>'+esc(note)+'</small></div></div>';
 const quick=(icon,label,page)=>'<button class="dash-action" onclick="loadPage(\''+page+'\')">'+icon+' '+label+'</button>';
 const trendBars=trend.length?trend.map(x=>{const c=Math.max(0,Number(x.collection||0)),e=Math.max(0,Number(x.expenses||0));return '<div class="bar-day" title="'+esc(shortDay(x.day))+' · Collection '+esc(money(c))+' · Expense '+esc(money(e))+'"><div class="bars"><i class="bar collection" style="height:'+Math.max(4,Math.round(c/maxTrend*150))+'px"></i><i class="bar expense" style="height:'+Math.max(4,Math.round(e/maxTrend*150))+'px"></i></div><small>'+esc(shortDay(x.day))+'</small></div>'}).join(''):'<div class="muted" style="padding:50px 0;text-align:center;width:100%">No financial activity for the last 7 days.</div>';
 const activityRows=activities.slice(0,8).map(x=>'<tr><td style="padding:10px 8px;font-weight:800">'+esc(x.action)+'</td><td style="padding:10px 8px;color:#66728e">'+esc(x.details||'—')+'</td><td style="padding:10px 8px;color:#8d97aa;white-space:nowrap">'+esc(x.created_at||'')+'</td></tr>').join('');
 const birthdayRows=birthdays.slice(0,5).map(x=>'<div class="dash-list-row"><div class="dash-list-avatar">🎂</div><div><b>'+esc(x.name)+'</b><small>'+esc(x.phone||x.member_id||'')+'</small></div><strong>'+esc(shortDay(x.date_of_birth))+'</strong></div>').join('');
 const expiryRows=expiry.slice(0,6).map(x=>{const d=String(x.validity_date||'');return '<div class="dash-list-row"><div class="dash-list-avatar warning">⏳</div><div><b>'+esc(x.name)+'</b><small>'+esc(x.membership_plan||x.member_id||'')+'</small></div><strong>'+esc(d)+'</strong></div>'}).join('');
 return '<div class="dashboard-page">'
 +' <section class="dash-hero"><div><div class="eyebrow">AR LIBRARY · MANAGEMENT OVERVIEW</div><h2>Good day, '+esc(name)+' 👋</h2><p>Here is today\'s library activity, collections and member status at a glance.</p></div><div class="dash-actions">'+quick('＋','Add Member','members')+quick('₹','Collect Fee','fees')+quick('✓','Attendance','attendance')+'<button class="dash-refresh" onclick="loadPage(\'dashboard\')">↻ Refresh</button></div></section>'
 +' <section class="dash-kpis">'
 +stat('👥','Total Members',s.members||0,(s.active||0)+' active members','blue')
 +stat('✓','Present Today',s.present||0,(s.checked_in||0)+' currently checked in','green')
 +stat('₹','Today Collection',money(s.today_paid),(s.month_paid?money(s.month_paid):'₹0')+' this month','amber')
 +stat('⚠','Pending Fees',money(s.pending_fees),'Outstanding member fees','violet')
 +' </section>'
 +' <section class="dash-grid-2"><div>'
 +'  <div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">LAST 7 DAYS</div><h3>Collection vs Expenses</h3></div><span class="live-pill">● Live</span></div><div class="chart-legend"><span><i class="legend-dot collection"></i>Collection</span><span><i class="legend-dot expense"></i>Expenses</span></div><div class="bar-chart">'+trendBars+'</div></div>'
 +'  <div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">RECENT ACTIVITY</div><h3>Latest updates</h3></div><button class="btn" onclick="loadPage(\'reports\')">View reports</button></div>'+(activityRows?table(['Action','Details','Time'],activityRows):'<div class="muted" style="padding:20px 0">No recent activity.</div>')+'</div>'
 +' </div><div>'
 +'  <div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">FINANCE</div><h3>This month</h3></div></div><div class="finance-kpis"><div class="finance-item"><span>Collection</span><strong>'+money(s.month_paid)+'</strong></div><div class="finance-item expense"><span>Expenses</span><strong>'+money(s.month_expenses)+'</strong></div><div class="finance-item net"><span>Net income</span><strong>'+money(s.month_net)+'</strong></div><div class="finance-item"><span>Open enquiries</span><strong>'+esc(s.open_enquiries||0)+'</strong></div></div></div>'
 +'  <div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">CAPACITY</div><h3>Seats & Lockers</h3></div></div><div class="capacity-wrap"><div class="capacity-line"><div><b>Seats</b><span>'+esc(s.occupied||0)+' occupied</span></div><strong>'+esc(s.available_seats||0)+' available</strong></div><div class="progress"><i style="width:'+Math.min(100,occ)+'%"></i></div><div class="capacity-line"><div><b>Lockers</b><span>'+esc(s.occupied_lockers||0)+' occupied</span></div><strong>'+esc(s.available_lockers||0)+' available</strong></div><div class="progress"><i style="width:'+Math.min(100,lockerOcc)+'%"></i></div></div></div>'
 +'  <div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">MEMBERSHIP HEALTH</div><h3>Status overview</h3></div></div><div class="membership-overview"><div class="membership-stat"><i class="dot active"></i><div><b>'+esc(s.active||0)+'</b><small>Active</small></div></div><div class="membership-stat"><i class="dot warning"></i><div><b>'+esc(s.expiring||0)+'</b><small>Expiring in 7 days</small></div></div><div class="membership-stat"><i class="dot danger"></i><div><b>'+esc(s.expired||0)+'</b><small>Expired</small></div></div><div class="membership-stat"><i class="dot info"></i><div><b>'+esc(s.converted_enquiries||0)+'</b><small>Converted enquiries</small></div></div></div></div>'
 +' </div></section>'
 +' <section class="dash-grid-2"><div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">UPCOMING</div><h3>Birthdays</h3></div></div>'+(birthdayRows||'<div class="muted">No birthdays in the next 7 days.</div>')+'</div><div class="dash-panel"><div class="dash-panel-head"><div><div class="eyebrow">ATTENTION NEEDED</div><h3>Membership expiry</h3></div><button class="btn" onclick="loadPage(\'members\')">View members</button></div>'+(expiryRows||'<div class="muted">No memberships expiring in the next 7 days.</div>')+'</div></section>'
 +'</div>';
}
async function loadDashboard(){const d=await api('dashboard');if(!d||!d.stats)throw Error((d&&d.message)||'Dashboard data was not returned by the server.');$('content').innerHTML=dashboard(d)}

async function members(){const d=await req('members_api.php?action=list');const rows=d.members||[];$('content').innerHTML=card('<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">Members</h2><p style="color:#68748d">Manage library members and open their profiles.</p></div><button class="btn primary" onclick="newMember()">+ Add Member</button></div><div style="margin:16px 0">'+input('Search','memberSearch')+'</div>'+table(['Member ID','Name','Phone','Plan','Shift','Validity','Status','Action'],rows.map(m=>'<tr><td style="padding:9px">'+esc(m.member_id)+'</td><td style="padding:9px;font-weight:700">'+esc(m.name)+'</td><td style="padding:9px">'+esc(m.phone||'—')+'</td><td style="padding:9px">'+esc(m.membership_plan||'—')+'</td><td style="padding:9px">'+esc(m.shift||'—')+'</td><td style="padding:9px">'+esc(m.validity_date||'—')+'</td><td style="padding:9px">'+esc(m.status)+'</td><td style="padding:9px;white-space:nowrap"><a class="btn" style="padding:7px 10px;text-decoration:none" href="member_profile.php?id='+encodeURIComponent(m.id)+'">Open</a> <button class="btn" onclick="editMember('+Number(m.id)+')">Edit</button></td></tr>').join('')||'<tr><td colspan="8" style="padding:15px">No members found.</td></tr>')+'</div>');const search=$('memberSearch');if(search)search.addEventListener('input',()=>{const q=search.value.toLowerCase();document.querySelectorAll('#content tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')})}
function modal(title,body){let m=$('globalModal');if(!m){m=document.createElement('div');m.id='globalModal';m.style.cssText='position:fixed;inset:0;background:rgba(10,20,40,.45);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px';document.body.appendChild(m)}m.innerHTML='<div style="background:#fff;width:min(760px,100%);max-height:90vh;overflow:auto;border-radius:16px;padding:22px"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">'+esc(title)+'</h2><button onclick="closeModal()" style="border:0;background:none;font-size:24px">×</button></div><div style="margin-top:18px">'+body+'</div></div>';}
window.closeModal=()=>{$('globalModal')?.remove()};
window.newMember=function(){modal('Add Member','<form id="memberForm">'+input('Member ID','member_id','AR-'+Date.now().toString().slice(-6))+input('Name','name')+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">'+input('Phone','phone')+input('Email','email','', 'email')+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">'+select('Plan','membership_plan',[['1 Month','1 Month'],['3 Months','3 Months'],['6 Months','6 Months']])+select('Shift','shift',[['Full Day','Full Day'],['Morning Shift','Morning Shift'],['Evening Shift','Evening Shift']])+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">'+input('Joining Date','joining_date',today(),'date')+input('Validity Date','validity_date',today(),'date')+'</div>'+input('Address','address')+buttons()+'</form>');$('memberForm').onsubmit=async e=>{e.preventDefault();try{await req('members_api.php?action=create',{method:'POST',body:new FormData(e.target)});closeModal();members()}catch(x){alert(x.message)}}};
window.editMember=async function(id){const d=await req('members_api.php?action=get&id='+id),m=d.member;modal('Edit Member','<form id="memberForm">'+input('Member ID','member_id',m.member_id)+input('Name','name',m.name)+input('Phone','phone',m.phone||'')+input('Email','email',m.email||'','email')+select('Plan','membership_plan',[['1 Month','1 Month'],['3 Months','3 Months'],['6 Months','6 Months']],m.membership_plan)+select('Shift','shift',[['Full Day','Full Day'],['Morning Shift','Morning Shift'],['Evening Shift','Evening Shift']],m.shift)+input('Joining Date','joining_date',m.joining_date||'','date')+input('Validity Date','validity_date',m.validity_date||'','date')+select('Status','status',[['Active','Active'],['Inactive','Inactive'],['Expired','Expired']],m.status)+input('Address','address',m.address||'')+buttons()+'</form>');$('memberForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);f.append('id',id);try{await req('members_api.php?action=update',{method:'POST',body:f});closeModal();members()}catch(x){alert(x.message)}}};

async function fees(){const [d,dues]=await Promise.all([payApi('list'),payApi('dues')]);const rows=d.payments||d.data||[];const ds=dues.members||[];$('content').innerHTML=card('<div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><div><h2 style="margin:0">Fees & Payments</h2><p style="color:#68748d">Record payments and view pending dues.</p></div><button class="btn primary" onclick="addPayment()">+ Record Payment</button></div><h3>Payments</h3>'+table(['Receipt','Member','Amount','Date','Method','Plan'],rows.map(x=>'<tr><td style="padding:9px">'+esc(x.receipt_no)+'</td><td style="padding:9px">'+esc(x.member_name||x.member_code)+'</td><td style="padding:9px">'+money(x.amount)+'</td><td style="padding:9px">'+esc(x.payment_date)+'</td><td style="padding:9px">'+esc(x.payment_method)+'</td><td style="padding:9px">'+esc(x.plan||'—')+'</td></tr>').join('')||'<tr><td colspan="6" style="padding:12px">No payments found.</td></tr>')+'<h3 style="margin-top:25px">Pending / Due Members</h3>'+table(['Member','Phone','Plan','Due Date','Amount','Status'],ds.map(x=>'<tr><td style="padding:9px">'+esc(x.name)+' ('+esc(x.member_id)+')</td><td style="padding:9px">'+esc(x.phone||'—')+'</td><td style="padding:9px">'+esc(x.membership_plan||'—')+'</td><td style="padding:9px">'+esc(x.due_date||'—')+'</td><td style="padding:9px">'+money(x.due_amount)+'</td><td style="padding:9px">Due</td></tr>').join('')||'<tr><td colspan="6" style="padding:12px">No pending dues.</td></tr>')+'</div>')}
window.addPayment=async function(){const m=await req('members_api.php?action=list');modal('Record Payment','<form id="payForm">'+select('Member','member_id',m.members.map(x=>[String(x.id),x.member_id+' — '+x.name]))+input('Fee Amount','fee_amount','','number')+input('Additional Charges','additional_charges','0','number')+input('Payment Date','payment_date',today(),'date')+select('Payment Method','payment_method',[['Cash','Cash'],['UPI','UPI'],['Online','Online'],['Bank','Bank'],['Card','Card'],['Other','Other']])+select('Payment Type','payment_type',[['Full','Full'],['Split','Split']])+input('Plan','plan','')+input('Notes','notes','')+buttons()+'</form>');$('payForm').onsubmit=async e=>{e.preventDefault();try{const d=await payApi('add',{method:'POST',body:new FormData(e.target)});alert(d.message+(d.receipt_no?'\nReceipt: '+d.receipt_no:''));closeModal();fees()}catch(x){alert(x.message)}}};

async function attendance(){const d=await api('attendance&date='+today());const rows=d.attendance||[];$('content').innerHTML=card('<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">Attendance</h2><p style="color:#68748d">Today: '+today()+'</p></div><button class="btn primary" onclick="markAttendance()">+ Check In / Out</button></div>'+table(['Member','Phone','Check In','Check Out','Status','Action'],rows.map(x=>'<tr><td style="padding:9px">'+esc(x.name)+' ('+esc(x.member_id)+')</td><td style="padding:9px">'+esc(x.phone||'—')+'</td><td style="padding:9px">'+esc(x.check_in_time||'—')+'</td><td style="padding:9px">'+esc(x.check_out_time||'—')+'</td><td style="padding:9px">'+esc(x.status)+'</td><td style="padding:9px">'+(x.check_out?'—':'<button class="btn" onclick="checkout('+Number(x.id)+')">Check Out</button>')+'</td></tr>').join('')||'<tr><td colspan="6" style="padding:12px">No attendance today.</td></tr>')+'</div>')}
window.markAttendance=async function(){const m=await req('members_api.php?action=list');modal('Attendance','<form id="attForm">'+select('Member','member_id',m.members.filter(x=>String(x.status).toLowerCase()==='active').map(x=>[String(x.id),x.member_id+' — '+x.name]))+select('Action','action',[['in','Check In'],['out','Check Out']])+input('Remarks','remarks','')+buttons()+'</form>');$('attForm').onsubmit=async e=>{e.preventDefault();try{alert((await api('attendance',{method:'POST',body:new FormData(e.target)})).message);closeModal();attendance()}catch(x){alert(x.message)}}};window.checkout=async id=>{try{alert((await api('checkout',{method:'POST',body:form({attendance_id:id})})).message);attendance()}catch(e){alert(e.message)}};

async function enquiry(){const d=await api('enquiries');const rows=d.enquiries||[];$('content').innerHTML=card('<div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">Enquiries</h2><p style="color:#68748d">Track prospective members and follow-ups.</p></div><button class="btn primary" onclick="newEnquiry()">+ Add Enquiry</button></div>'+table(['Name','Phone','Requirement','Follow Up','Status','Action'],rows.map(x=>'<tr><td style="padding:9px">'+esc(x.name)+'</td><td style="padding:9px">'+esc(x.phone||'—')+'</td><td style="padding:9px">'+esc(x.requirement||'—')+'</td><td style="padding:9px">'+esc(x.follow_up||'—')+'</td><td style="padding:9px">'+esc(x.status)+'</td><td style="padding:9px">'+(x.status!=='Converted'?'<button class="btn" onclick="convertEnquiry('+Number(x.id)+')">Convert</button>':'')+' <button class="btn" onclick="editEnquiry('+Number(x.id)+')">Edit</button></td></tr>').join('')||'<tr><td colspan="6" style="padding:12px">No enquiries.</td></tr>')+'</div>')}
window.newEnquiry=function(x={}){modal(x.id?'Edit Enquiry':'Add Enquiry','<form id="enqForm">'+input('Name','name',x.name||'')+input('Phone','phone',x.phone||'')+input('Requirement','requirement',x.requirement||'')+input('Follow Up','follow_up',x.follow_up||'','date')+select('Status','status',[['Open','Open'],['Contacted','Contacted'],['Converted','Converted'],['Closed','Closed']],x.status||'Open')+input('Notes','notes',x.notes||'')+buttons()+'</form>');$('enqForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(x.id)f.append('id',x.id);try{alert((await api('enquiries',{method:'POST',body:f})).message);closeModal();enquiry()}catch(z){alert(z.message)}}};window.editEnquiry=async id=>{const d=await api('enquiries');const x=(d.enquiries||[]).find(a=>Number(a.id)===Number(id));if(x)newEnquiry(x)};window.convertEnquiry=async id=>{if(!confirm('Convert this enquiry to a member?'))return;try{alert((await req('admin_api.php?action=enquiries&convert=1',{method:'POST',body:form({id, membership_plan:'1 Month',shift:'Full Day',joining_date:today(),validity_date:today()})})).message);enquiry()}catch(e){alert(e.message)}};

async function expenses(){const d=await api('expenses');const rows=d.expenses||[];$('content').innerHTML=card('<div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">Expenses</h2><p style="color:#68748d">This month: <b>'+money(d.month_total)+'</b></p></div><button class="btn primary" onclick="newExpense()">+ Add Expense</button></div>'+table(['Date','Category','Description','Amount','Method','Vendor','Action'],rows.map(x=>'<tr><td style="padding:9px">'+esc(x.expense_date)+'</td><td style="padding:9px">'+esc(x.category)+'</td><td style="padding:9px">'+esc(x.description||'—')+'</td><td style="padding:9px">'+money(x.amount)+'</td><td style="padding:9px">'+esc(x.payment_method)+'</td><td style="padding:9px">'+esc(x.vendor||'—')+'</td><td style="padding:9px"><button class="btn" onclick="editExpense('+Number(x.id)+')">Edit</button></td></tr>').join('')||'<tr><td colspan="7" style="padding:12px">No expenses.</td></tr>')+'</div>')};
window.newExpense=function(x={}){modal(x.id?'Edit Expense':'Add Expense','<form id="expForm">'+input('Date','expense_date',x.expense_date||today(),'date')+input('Category','category',x.category||'')+input('Description','description',x.description||'')+input('Amount','amount',x.amount||'','number')+select('Payment Method','payment_method',[['Cash','Cash'],['UPI','UPI'],['Online','Online'],['Bank','Bank'],['Card','Card'],['Other','Other']],x.payment_method||'Cash')+input('Vendor','vendor',x.vendor||'')+input('Notes','notes',x.notes||'')+buttons()+'</form>');$('expForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(x.id)f.append('id',x.id);try{alert((await api('expenses',{method:'POST',body:f})).message);closeModal();expenses()}catch(z){alert(z.message)}}};window.editExpense=async id=>{const d=await api('expenses');const x=(d.expenses||[]).find(a=>Number(a.id)===Number(id));if(x)newExpense(x)};

async function reports(){const from=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),to=today();const d=await api('report&type=summary&from='+from+'&to='+to);const s=d.data||{};$('content').innerHTML=card('<h2 style="margin-top:0">Reports</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px">'+[['Members',s.members],['Attendance',s.attendance],['Fees',money(s.fees)],['Expenses',money(s.expenses)],['Net Income',money(s.net_income)],['Enquiries',s.enquiries]].map(x=>card('<small>'+x[0]+'</small><div style="font-size:24px;font-weight:900">'+esc(x[1])+'</div>')).join('')+'</div><div style="margin-top:18px">'+['members','fees','attendance','expenses'].map(t=>'<button class="btn" style="margin:4px" onclick="reportTable(\''+t+'\')">'+t[0].toUpperCase()+t.slice(1)+' Report</button>').join('')+'</div><div id="reportResult" style="margin-top:18px"></div></div>')};window.reportTable=async type=>{try{const from=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),to=today();const d=await api('report&type='+type+'&from='+from+'&to='+to);const data=Array.isArray(d.data)?d.data:[];if(!data.length){$('reportResult').innerHTML=card('No records found.');return}const heads=Object.keys(data[0]);$('reportResult').innerHTML=table(heads,data.map(r=>'<tr>'+heads.map(h=>'<td style="padding:8px">'+esc(r[h])+'</td>').join('')+'</tr>').join(''))}catch(e){alert(e.message)}};

async function staff(){const d=await api('staff');const rows=d.staff||[];$('content').innerHTML=card('<div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">Staff Management</h2><p style="color:#68748d">Manage admin and staff accounts.</p></div><button class="btn primary" onclick="newStaff()">+ Add Staff</button></div>'+table(['Staff ID','Name','Role','Status','Permissions','Action'],rows.map(x=>'<tr><td style="padding:9px">'+esc(x.staff_id)+'</td><td style="padding:9px">'+esc(x.name)+'</td><td style="padding:9px">'+esc(x.role)+'</td><td style="padding:9px">'+esc(x.status)+'</td><td style="padding:9px">'+esc((x.permissions||[]).join(', '))+'</td><td style="padding:9px"><button class="btn" onclick="editStaff('+Number(x.id)+')">Edit</button> <button class="btn" onclick="deleteStaff('+Number(x.id)+')">Delete</button></td></tr>').join(''))+'</div>')};
const permList=['dashboard','seats','members','fees','attendance','attendance_qr','enquiry','expenses','reports','backup','settings'];
window.newStaff=function(x={}){modal(x.id?'Edit Staff':'Add Staff','<form id="staffForm">'+input('Staff ID','staff_id',x.staff_id||'STF-')+input('Name','name',x.name||'')+input('Password','password','', 'password')+select('Role','role',[['staff','Staff'],['admin','Admin']],x.role||'staff')+select('Status','status',[['active','Active'],['inactive','Inactive']],x.status||'active')+'<label style="font-weight:800">Permissions</label><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:8px 0 16px">'+permList.map(p=>'<label style="font-weight:600"><input type="checkbox" name="perm" value="'+p+'" '+((x.permissions||[]).includes(p)?'checked':'')+'> '+p+'</label>').join('')+'</div>'+buttons()+'</form>');$('staffForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(x.id)f.append('id',x.id);f.append('permissions',JSON.stringify([...e.target.querySelectorAll('input[name=perm]:checked')].map(a=>a.value)));try{alert((await api('staff',{method:'POST',body:f})).message);closeModal();staff()}catch(z){alert(z.message)}}};window.editStaff=async id=>{const d=await api('staff');const x=(d.staff||[]).find(a=>Number(a.id)===Number(id));if(x)newStaff(x)};window.deleteStaff=async id=>{if(!confirm('Delete this staff account?'))return;try{alert((await api('staff&id='+id,{method:'DELETE'})).message);staff()}catch(e){alert(e.message)}};

async function settings(){const d=await api('settings');const s=d.settings||{};$('content').innerHTML=card('<h2 style="margin-top:0">Settings</h2><form id="settingsForm"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">'+input('Library Name','library_name',s.library_name||'AR Library')+input('Phone','phone',s.phone||'')+input('Opening Time','opening_time',s.opening_time||'06:00','time')+input('Closing Time','closing_time',s.closing_time||'22:00','time')+input('Monthly Fee','monthly_fee',s.monthly_fee||'','number')+input('Total Seats','total_seats',s.total_seats||79,'number')+input('Total Lockers','total_lockers',s.total_lockers||79,'number')+input('Morning End','morning_end',s.morning_end||'13:00','time')+input('Evening Start','evening_start',s.evening_start||'13:00','time')+input('Attendance Latitude','attendance_latitude',s.attendance_latitude||'')+input('Attendance Longitude','attendance_longitude',s.attendance_longitude||'')+input('Attendance Radius (m)','attendance_radius_meters',s.attendance_radius_meters||100,'number')+'</div>'+input('Address','address',s.address||'')+input('Receipt Footer','receipt_footer',s.receipt_footer||'')+buttons()+'</form>');$('settingsForm').onsubmit=async e=>{e.preventDefault();try{alert((await api('settings',{method:'POST',body:new FormData(e.target)})).message)}catch(x){alert(x.message)}}}
function backup(){$('content').innerHTML=card('<h2 style="margin-top:0">Backup & Restore</h2><p>Create a complete SQL backup or restore a previous backup.</p><p><a class="btn primary" href="backup.php">⬇ Download Database Backup</a></p><hr><form id="restoreForm" enctype="multipart/form-data"><label style="font-weight:800">SQL Backup File<input name="backup_file" type="file" accept=".sql" required style="display:block;margin:8px 0"></label>'+buttons()+'</form>');$('restoreForm').onsubmit=async e=>{e.preventDefault();if(!confirm('Restore database from this backup? A safety backup will be created first.'))return;try{alert((await req('restore.php',{method:'POST',body:new FormData(e.target)})).message);location.reload()}catch(x){alert(x.message)}}}
async function seats(){location.href='seats.php'}
async function qr(){location.href='qr_display.php'}
window.loadPage=async function(p){p=String(p||'dashboard');active(p);const titles={dashboard:'Dashboard',seats:'Seats & Lockers',members:'Members',fees:'Fees & Payments',attendance:'Attendance',attendance_qr:'Attendance QR',enquiry:'Enquiry',expenses:'Expenses',reports:'Reports',staff:'Staff Management',backup:'Backup & Restore',settings:'Settings'};setTitle(titles[p]||'Dashboard');loading();try{if(p==='dashboard')return await loadDashboard();if(p==='members')return await members();if(p==='fees')return await fees();if(p==='attendance')return await attendance();if(p==='enquiry')return await enquiry();if(p==='expenses')return await expenses();if(p==='reports')return await reports();if(p==='staff')return await staff();if(p==='backup')return backup();if(p==='settings')return await settings();if(p==='seats')return seats();if(p==='attendance_qr')return qr();await loadDashboard()}catch(e){console.error(e);fail(e)}};
function clock(){const e=$('headerDateTime');if(e)e.textContent=new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}
document.addEventListener('DOMContentLoaded',()=>{clock();setInterval(clock,1000);if($('app')&&!$('app').classList.contains('hidden'))loadPage('dashboard')});
})();
