<?php
require_once __DIR__ . '/security.php';
require_once __DIR__ . '/db.php';
require_permission('seats');
if (!isset($_SESSION['staff_id'])) { header('Location: index.php'); exit; }
?>
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AR Library · Seat & Locker Command Center</title>
<?php require_once __DIR__ . '/security.php'; ?>
<meta name="csrf-token" content="<?=htmlspecialchars(csrf_token(),ENT_QUOTES,'UTF-8')?>">
<style>
:root{--navy:#111b34;--navy2:#1b2a4a;--ink:#1b2942;--muted:#7a879d;--line:#e7ebf2;--bg:#f4f6fa;--card:#fff;--accent:#4358e8;--green:#19a36f;--orange:#f39a2f;--red:#db4d55;--gold:#d69b28;--shadow:0 14px 40px rgba(20,35,70,.08)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Arial,sans-serif}.page{max-width:1580px;margin:auto;padding:22px}.hero{background:linear-gradient(135deg,#111b34,#243b68);color:#fff;border-radius:22px;padding:22px 24px;display:flex;justify-content:space-between;align-items:center;gap:18px;box-shadow:0 18px 45px rgba(17,27,52,.18);margin-bottom:16px}.hero-left{display:flex;align-items:center;gap:14px}.brand{width:48px;height:48px;border-radius:15px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.16);display:grid;place-items:center;font-weight:950;letter-spacing:-1px}.eyebrow{font-size:9px;letter-spacing:1.8px;font-weight:900;color:#aebdff}.hero h1{font-size:25px;margin:3px 0 5px}.hero p{font-size:11px;margin:0;color:#d3dbeb}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #dce2ec;background:#fff;color:var(--ink);padding:10px 14px;border-radius:11px;font-weight:850;font-size:11px;cursor:pointer}.btn.dark{background:rgba(255,255,255,.1);border-color:rgba(255,255,255,.2);color:#fff}.btn.primary{background:var(--accent);border-color:var(--accent);color:#fff}.btn:hover{transform:translateY(-1px)}
.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:16px}.kpi{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:15px;box-shadow:var(--shadow)}.kpi-top{display:flex;justify-content:space-between;align-items:center}.kpi-label{font-size:9px;font-weight:900;letter-spacing:.9px;text-transform:uppercase;color:var(--muted)}.kpi-icon{width:32px;height:32px;border-radius:10px;background:#f0f2ff;display:grid;place-items:center}.kpi-value{font-size:25px;font-weight:950;margin-top:7px}.kpi-foot{font-size:9px;color:var(--muted);margin-top:2px}
.controls{background:#fff;border:1px solid var(--line);border-radius:16px;padding:11px;display:flex;align-items:center;gap:9px;box-shadow:var(--shadow);margin-bottom:16px}.search{height:40px;display:flex;align-items:center;gap:8px;background:#f8f9fc;border:1px solid var(--line);border-radius:10px;padding:0 12px;flex:1;max-width:430px}.search span{font-size:15px;color:#8b96a9}.search input{width:100%;border:0;outline:0;background:transparent;font-size:11px}.tabs{display:flex;gap:6px}.tab{height:38px;padding:0 13px;border:1px solid var(--line);background:#fff;border-radius:9px;font-size:10px;font-weight:900;color:#68758c;cursor:pointer}.tab.active{background:var(--navy);border-color:var(--navy);color:#fff}.control-note{margin-left:auto;font-size:9px;color:var(--muted);font-weight:700}
.main{display:grid;grid-template-columns:minmax(0,1fr) 350px;gap:16px}.card{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);overflow:hidden}.card-head{padding:17px 18px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px}.card-head h2{font-size:13px;margin:0}.card-head p{font-size:9px;color:var(--muted);margin:4px 0 0}.pill{font-size:9px;font-weight:900;padding:7px 9px;border-radius:8px;background:#f0f2f7;color:#59657c}.map{padding:17px}.front{height:38px;border-radius:11px;border:1px dashed #cbd3e0;background:#fafbfe;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:950;letter-spacing:1.5px;color:#8a95a8;margin-bottom:13px}.shift{border:1px solid var(--line);border-radius:15px;margin-bottom:12px;overflow:hidden}.shift:last-child{margin-bottom:0}.shift-head{padding:12px 14px;background:#fbfcfe;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.shift-title{display:flex;align-items:center;gap:9px}.dot{width:9px;height:9px;border-radius:50%}.dot.m{background:var(--green)}.dot.e{background:var(--orange)}.dot.f{background:var(--red)}.shift-title b{font-size:11px}.shift-title small{display:block;color:var(--muted);font-size:8px;margin-top:2px}.shift-stat{font-size:9px;font-weight:850;color:#68758c}.seat-grid{padding:14px;display:grid;grid-template-columns:repeat(10,minmax(38px,1fr));gap:7px}.row-label{grid-column:1/-1;font-size:8px;font-weight:950;color:#a0a9b9;letter-spacing:1.1px;padding-top:2px}.aisle{grid-column:1/-1;border-top:1px dashed #e2e6ee;height:4px;margin:2px 0}.seat{height:58px;border-radius:12px;border:1px solid #dce2ec;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px;cursor:pointer;transition:.15s;overflow:hidden;position:relative}.seat:hover{transform:translateY(-2px);box-shadow:0 9px 20px rgba(20,35,70,.13)}.seat .chair{font-size:17px;line-height:17px}.seat b{font-size:9px}.seat small{font-size:7px;max-width:90%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.seat.available{color:#5c6a81;background:#fbfcfe}.seat.occupied.morning{background:#e7f8f0;border-color:#8bd1b2;color:#106d4b}.seat.occupied.evening{background:#fff1df;border-color:#efbd7a;color:#8b4d08}.seat.occupied.full{background:#fbe7e8;border-color:#e6a0a5;color:#972f35}.seat.reserved{background:#fff8df;border-color:#e6c66d;color:#8a650c}.seat.dim{display:none}.seat.hit{outline:2px solid var(--accent);outline-offset:2px}
.side{display:flex;flex-direction:column;gap:16px}.legend{padding:16px}.legend-row{display:flex;align-items:center;gap:8px;font-size:10px;margin:10px 0;color:#5f6c83}.sw{width:13px;height:13px;border-radius:4px;border:1px solid #d7dde8}.sw.free{background:#fbfcfe}.sw.m{background:#e7f8f0;border-color:#8bd1b2}.sw.e{background:#fff1df;border-color:#efbd7a}.sw.f{background:#fbe7e8;border-color:#e6a0a5}.sw.r{background:#fff8df;border-color:#e6c66d}.locker-head{display:flex;align-items:center;gap:10px}.locker-icon{width:34px;height:34px;border-radius:10px;background:#f8f0dc;display:grid;place-items:center}.locker-map{padding:15px;display:grid;grid-template-columns:repeat(7,minmax(34px,1fr));gap:6px}.locker{height:40px;border-radius:9px;border:1px solid #dce2ec;background:#f9fafc;display:grid;place-items:center;cursor:pointer;font-size:9px;font-weight:900;color:#65738a}.locker.occupied{background:#e8eefc;border-color:#9eaff2;color:#3148ae}.locker.expired{background:#fff0f0;border-color:#e5aaaa;color:#a53a3f}.locker:hover{transform:translateY(-1px)}.holder-list{padding:0 16px 14px}.holder{display:flex;align-items:center;gap:9px;padding:11px 0;border-top:1px solid var(--line)}.avatar{width:32px;height:32px;border-radius:10px;background:#eef1ff;color:var(--accent);display:grid;place-items:center;font-size:11px;font-weight:950}.holder-main{min-width:0;flex:1}.holder-main b{display:block;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.holder-main small{display:block;font-size:8px;color:var(--muted);margin-top:2px}.release{width:28px;height:28px;border:0;border-radius:8px;background:#fcebed;color:var(--red);font-weight:950;cursor:pointer}.empty{padding:16px;color:var(--muted);font-size:10px}
.modalback{position:fixed;inset:0;background:rgba(8,17,37,.62);display:grid;place-items:center;padding:16px;z-index:100}.modal{width:min(540px,100%);background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 28px 80px rgba(0,0,0,.28)}.modalhead{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.modalhead h3{font-size:14px;margin:0}.close{border:0;width:31px;height:31px;border-radius:9px;background:#f2f4f8;cursor:pointer;font-size:17px}.form{padding:18px}.profile{display:flex;align-items:center;gap:12px;border:1px solid #e2e7f0;border-radius:14px;padding:13px;background:linear-gradient(135deg,#f6f8ff,#fff);margin-bottom:13px}.profile-avatar{width:48px;height:48px;border-radius:14px;background:var(--navy);color:#fff;display:grid;place-items:center;font-size:18px;font-weight:950}.profile-main{min-width:0;flex:1}.profile-name{font-size:15px;font-weight:950}.profile-meta{font-size:9px;color:var(--muted);margin-top:3px}.profile-tags{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.profile-tags span{font-size:8px;font-weight:900;background:#edf0f7;padding:4px 6px;border-radius:6px;color:#59657c}.booked{font-size:8px;font-weight:950;color:#0e6a48;background:#e4f7ed;border:1px solid #b8e3cc;padding:5px 7px;border-radius:7px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{margin-bottom:11px}.field label{display:block;font-size:9px;font-weight:950;margin-bottom:6px;color:#59657c}.field input{width:100%;height:40px;border:1px solid #d9dfeb;border-radius:9px;padding:0 10px;outline:0;font-size:11px}.modalfoot{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.toast{position:fixed;right:20px;bottom:20px;background:var(--navy);color:#fff;padding:11px 14px;border-radius:11px;font-size:10px;font-weight:850;display:none;z-index:200}
@media(max-width:1200px){.kpis{grid-template-columns:repeat(3,1fr)}.main{grid-template-columns:1fr}.side{display:grid;grid-template-columns:1fr 1fr}.seat-grid{grid-template-columns:repeat(10,minmax(30px,1fr))}}@media(max-width:760px){.page{padding:12px}.hero{padding:17px;align-items:flex-start}.hero h1{font-size:21px}.actions{width:100%}.controls{flex-direction:column;align-items:stretch}.search{max-width:none}.tabs{width:100%}.tab{flex:1}.control-note{display:none}.kpis{grid-template-columns:1fr 1fr}.side{grid-template-columns:1fr}.seat-grid{grid-template-columns:repeat(5,minmax(38px,1fr))}.seat{height:55px}.locker-map{grid-template-columns:repeat(5,minmax(34px,1fr))}.grid2{grid-template-columns:1fr}}
</style></head><body>
<div class="page">
<section class="hero"><div class="hero-left"><div class="brand">AR</div><div><div class="eyebrow">AR LIBRARY · OPERATIONS</div><h1>Seat & Locker Command Center</h1><p>Live seating, member assignment and locker management in one professional workspace.</p></div></div><div class="actions"><button class="btn dark" onclick="location.href='index.php'">← Dashboard</button><button class="btn primary" onclick="load()">↻ Refresh Live Data</button></div></section>
<div id="kpis" class="kpis"></div>
<section class="controls"><div class="search"><span>⌕</span><input id="search" placeholder="Search seat number, member name or ID…" oninput="applyFilters()"></div><div class="tabs"><button class="tab active" data-f="all" onclick="setFilter('all',this)">All Seats</button><button class="tab" data-f="available" onclick="setFilter('available',this)">Available</button><button class="tab" data-f="occupied" onclick="setFilter('occupied',this)">Occupied</button><button class="tab" data-f="reserved" onclick="setFilter('reserved',this)">Reserved</button></div><div class="control-note">Click any seat to view or manage assignment</div></section>
<div class="main"><main class="card"><div class="card-head"><div><h2>LIVE LIBRARY FLOOR MAP</h2><p>live-seat visual layout · availability updates from your MongoDB database</p></div><span class="pill" id="capacity">76 SEATS</span></div><div class="map"><div class="front">FRONT / BOARD · RECEPTION & ENTRANCE</div><div id="shifts"></div></div></main>
<aside class="side"><section class="card"><div class="card-head"><div class="locker-head"><div class="locker-icon">🔐</div><div><h2>LOCKER MANAGEMENT</h2><p>Assign, monitor and release lockers</p></div></div><span class="pill" id="lockerSummary">Loading…</span></div><div id="lockerLayout" class="locker-map"></div><div id="lockerHolders" class="holder-list"></div></section>
<section class="card"><div class="card-head"><div><h2>STATUS GUIDE</h2><p>Quick visual reference</p></div></div><div class="legend"><div class="legend-row"><i class="sw free"></i> Available</div><div class="legend-row"><i class="sw m"></i> Morning occupied</div><div class="legend-row"><i class="sw e"></i> Evening occupied</div><div class="legend-row"><i class="sw f"></i> Full Day occupied</div><div class="legend-row"><i class="sw r"></i> Reserved</div></div></section></aside></div>
</div><div id="modal"></div><div id="toast" class="toast"></div>
<script>
const seatNativeFetch=window.fetch.bind(window);
window.fetch=(input,init={})=>{const method=String(init.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){const h=new Headers(init.headers||{});const t=document.querySelector('meta[name="csrf-token"]')?.content||'';if(t)h.set('X-CSRF-Token',t);init.headers=h;}return seatNativeFetch(input,init);};
let rows=[],lockers=[],total=76,totalLockers=76,filter='all';window.settings={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const escJs=s=>String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ');
const norm=v=>{v=String(v??'').trim().toLowerCase().replace(/\s+/g,' ');if(v==='morning'||v==='morning shift')return 'Morning Shift';if(v==='evening'||v==='evening shift')return 'Evening Shift';if(v==='full'||v==='full day'||v==='full day shift')return 'Full Day';return String(v)};
const api=async action=>{const r=await fetch('admin_api.php?action='+encodeURIComponent(action),{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok||d.success===false)throw Error(d.message||'Request failed');return d};
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',2600)}
function conflicts(requested,x){if(!x)return false;const st=String(x.status??'').toLowerCase();if(st!=='assigned'&&st!=='reserved')return false;const s=norm(x.shift);if(requested==='Full Day')return ['Morning Shift','Evening Shift','Full Day'].includes(s);if(requested==='Morning Shift')return ['Morning Shift','Full Day'].includes(s);return ['Evening Shift','Full Day'].includes(s)}
function hours(t){const f=x=>{const [h,m]=String(x||'').split(':').map(Number);if(!Number.isFinite(h))return String(x||'');return `${(h%12)||12}:${String(m||0).padStart(2,'0')} ${h>=12?'PM':'AM'}`};if(t==='Morning Shift')return `${f(window.settings.opening_time||'08:00')} – ${f(window.settings.morning_end||'14:00')}`;if(t==='Evening Shift')return `${f(window.settings.evening_start||'14:00')} – ${f(window.settings.closing_time||'20:00')}`;return `${f(window.settings.opening_time||'08:00')} – ${f(window.settings.closing_time||'20:00')}`}
function load(){api('seats').then(d=>{rows=d.seats||[];lockers=d.lockers||[];total=Number(d.total_seats||76);totalLockers=Number(d.total_lockers||76);window.settings=d.settings||{};render();renderLockers()}).catch(e=>{document.getElementById('shifts').innerHTML=`<div class="empty">Could not load live data: ${esc(e.message)}</div>`})}
function render(){const shifts=[['Morning Shift','m'],['Evening Shift','e'],['Full Day','f']];let html='';shifts.forEach(([title,key])=>{const relevant=rows.filter(x=>conflicts(title,x));const by={};relevant.forEach(x=>{const n=String(x.seat_no).replace(/^S-0*/i,'');const sx=norm(x.shift);if(!by[n]||sx==='Full Day'||sx===title)by[n]=x});const occ=Object.values(by).filter(x=>String(x.status).toLowerCase()==='assigned').length;const res=Object.values(by).filter(x=>String(x.status).toLowerCase()==='reserved').length;const free=Math.max(0,total-occ-res);html+=`<section class="shift"><div class="shift-head"><div class="shift-title"><i class="dot ${key}"></i><div><b>${title}</b><small>${hours(title)}</small></div></div><div class="shift-stat">${free} Free · ${occ} Occupied${res?' · '+res+' Reserved':''}</div></div><div class="seat-grid">`;for(let start=1;start<=total;start+=20){const end=Math.min(total,start+19);html+=`<div class="row-label">ROW ${String.fromCharCode(65+Math.floor((start-1)/20))}</div>`;for(let n=start;n<=end;n++){const x=by[String(n)];const st=x?(String(x.status).toLowerCase()==='reserved'?'reserved':'occupied'):'available';const sx=x?norm(x.shift):title;const cc=sx==='Morning Shift'?'morning':sx==='Evening Shift'?'evening':'full';const label=x?(x.name||x.member_code||'Booked'):'Available';const search=(n+' '+label+' '+(x?.member_code||''));html+=`<button type="button" class="seat ${st} ${st==='occupied'?cc:''}" data-search="${esc(search)}" data-state="${st}" title="${esc('Seat '+n+' · '+label+' · '+sx)}" onclick="openSeat(${x?Number(x.id):0},${n},'${escJs(x?norm(x.shift):title)}')"><span class="chair">💺</span><b>${n}</b><small>${esc(label)}</small></button>`}if(end<total)html+='<div class="aisle"></div>'}html+='</div></section>'});document.getElementById('shifts').innerHTML=html;document.getElementById('capacity').textContent=total+' SEATS';renderKpis();applyFilters()}
function renderKpis(){const assigned=rows.filter(x=>String(x.status).toLowerCase()==='assigned');const reserved=rows.filter(x=>String(x.status).toLowerCase()==='reserved');const used=new Set([...assigned,...reserved].map(x=>String(x.seat_no).replace(/^S-0*/i,''))).size;const free=Math.max(0,total-used);const fill=total?Math.round(assigned.length/total*100):0;const la=lockers.filter(x=>String(x.status).toLowerCase()==='assigned').length;const lf=Math.max(0,totalLockers-la);document.getElementById('kpis').innerHTML=`<div class="kpi"><div class="kpi-top"><span class="kpi-label">Total Seats</span><span class="kpi-icon">💺</span></div><div class="kpi-value">${total}</div><div class="kpi-foot">Library capacity</div></div><div class="kpi"><div class="kpi-top"><span class="kpi-label">Available</span><span class="kpi-icon">✓</span></div><div class="kpi-value">${free}</div><div class="kpi-foot">Ready for booking</div></div><div class="kpi"><div class="kpi-top"><span class="kpi-label">Occupied</span><span class="kpi-icon">●</span></div><div class="kpi-value">${assigned.length}</div><div class="kpi-foot">${fill}% current allocation</div></div><div class="kpi"><div class="kpi-top"><span class="kpi-label">Reserved</span><span class="kpi-icon">◆</span></div><div class="kpi-value">${reserved.length}</div><div class="kpi-foot">Pending reservations</div></div><div class="kpi"><div class="kpi-top"><span class="kpi-label">Free Lockers</span><span class="kpi-icon">🔐</span></div><div class="kpi-value">${lf}</div><div class="kpi-foot">${la} assigned of ${totalLockers}</div></div>`}
function applyFilters(){const q=(document.getElementById('search')?.value||'').toLowerCase().trim();document.querySelectorAll('.seat').forEach(e=>{const okText=!q||(e.dataset.search||'').toLowerCase().includes(q);const okState=filter==='all'||e.dataset.state===filter;e.classList.toggle('dim',!(okText&&okState));e.classList.toggle('hit',!!q&&okText&&okState)})}
function setFilter(f,b){filter=f;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');applyFilters()}
function openSeat(id,n,shift){const cur=id?rows.find(x=>Number(x.id)===Number(id)):null;const booked=!!cur;const name=cur?.name||'';const code=cur?.member_code||'';const initials=(name||'M').trim().charAt(0).toUpperCase();let profile=booked?`<div class="profile"><div class="profile-avatar">${esc(initials)}</div><div class="profile-main"><div class="profile-name">${esc(name||'Member')}</div><div class="profile-meta">${esc(code||'Member ID unavailable')}</div><div class="profile-tags"><span>SEAT ${esc(n)}</span><span>${esc(shift)}</span></div></div><span class="booked">BOOKED</span></div>`:'';let details=booked?`<div class="grid2"><div class="field"><label>MEMBER</label><input value="${esc(name)}" readonly></div><div class="field"><label>MEMBER ID</label><input value="${esc(code)}" readonly></div><div class="field"><label>SEAT</label><input value="${esc(n)}" readonly></div><div class="field"><label>SHIFT</label><input value="${esc(shift)}" readonly></div><div class="field"><label>START DATE</label><input value="${esc(cur?.start_date||'—')}" readonly></div><div class="field"><label>VALID TILL</label><input value="${esc(cur?.end_date||'—')}" readonly></div></div>`:`<div class="grid2"><div class="field"><label>SEAT</label><input value="${esc(n)}" readonly></div><div class="field"><label>SHIFT</label><input value="${esc(shift)}" readonly></div></div>`;const profileBtn=booked&&cur?.member_id?`<button class="btn" onclick="location.href='member_profile.php?id=${encodeURIComponent(cur.member_id)}'">View Member Profile</button>`:'';document.getElementById('modal').innerHTML=`<div class="modalback"><div class="modal"><div class="modalhead"><h3>${booked?'Booked Seat':'Assign Seat'} · ${esc(n)}</h3><button class="close" onclick="closeModal()">×</button></div><div class="form">${profile}${details}<div class="field"><label>MEMBER ID / MEMBER CODE</label><input id="seatMember" value="${esc(code)}" placeholder="Example: MEM-001"></div><div class="modalfoot">${profileBtn}<button class="btn" onclick="closeModal()">Cancel</button>${booked?`<button class="btn" onclick="releaseSeat(${Number(id)})">Release</button>`:''}<button class="btn primary" onclick="saveSeat(${id||0},${n},'${escJs(shift)}')">${booked?'Update Assignment':'Assign Seat'}</button></div></div></div></div>`}
async function saveSeat(id,n,shift){const m=document.getElementById('seatMember').value.trim();if(!m)return toast('Member ID / code is required.');const f=new FormData();f.append('seat_no',n);f.append('shift',shift);f.append('member_id',m);if(id)f.append('id',id);try{const r=await fetch('admin_api.php?action=assign_seat',{method:'POST',body:f,credentials:'same-origin'});const d=await r.json();if(!r.ok||d.success===false)throw Error(d.message||'Could not save seat');closeModal();toast(d.message||'Seat saved successfully');load()}catch(e){toast(e.message)}}
async function releaseSeat(id){if(!confirm('Release this seat?'))return;try{const r=await fetch('admin_api.php?action=release_seat',{method:'POST',body:new URLSearchParams({id:String(id)}),credentials:'same-origin'});const d=await r.json();if(!r.ok||d.success===false)throw Error(d.message||'Could not release seat');closeModal();toast(d.message||'Seat released');load()}catch(e){toast(e.message)}}
function closeModal(){document.getElementById('modal').innerHTML=''}
function renderLockers(){const box=document.getElementById('lockerLayout');const assigned={};lockers.forEach(x=>assigned[String(x.locker_no)]=x);let h='';for(let n=1;n<=totalLockers;n++){const x=assigned[String(n)];const st=x?(String(x.status).toLowerCase()==='expired'?'expired':'occupied'):'available';h+=`<button type="button" class="locker ${st}" title="${esc(x?('Locker '+n+' · '+(x.name||'Assigned')):('Locker '+n+' · Available'))}" onclick="openLocker(${n},${x?Number(x.id):0})">${n}</button>`}box.innerHTML=h;const active=lockers.filter(x=>String(x.status).toLowerCase()==='assigned').length;const expired=lockers.filter(x=>String(x.status).toLowerCase()==='expired').length;document.getElementById('lockerSummary').textContent=`${Math.max(0,totalLockers-active-expired)} FREE · ${active} USED`;const holder=document.getElementById('lockerHolders');holder.innerHTML=lockers.length?lockers.map(x=>`<div class="holder"><span class="avatar">🔐</span><div class="holder-main"><b>Locker ${esc(x.locker_no)} · ${esc(x.name||'Unknown')}</b><small>${esc(x.member_code||'')} · ${esc(x.status)} · ${esc(x.end_date||'No end date')}</small></div><button class="release" onclick="releaseLocker(${Number(x.id)})">×</button></div>`).join(''):'<div class="empty">No locker assignments.</div>'}
function openLocker(no,id){const cur=id?lockers.find(x=>Number(x.id)===Number(id)):null;const today=new Date().toISOString().slice(0,10);document.getElementById('modal').innerHTML=`<div class="modalback"><div class="modal"><div class="modalhead"><h3>${cur?'Edit Locker':'Assign Locker'} · ${esc(no)}</h3><button class="close" onclick="closeModal()">×</button></div><div class="form"><div class="grid2"><div class="field"><label>LOCKER NUMBER</label><input id="lockerNo" type="number" min="1" max="${totalLockers}" value="${esc(no)}"></div><div class="field"><label>MEMBER ID / CODE</label><input id="lockerMember" value="${esc(cur?.member_code||'')}" placeholder="MEM-001"></div><div class="field"><label>START DATE</label><input id="lockerStart" type="date" value="${esc(cur?.start_date||today)}"></div><div class="field"><label>END DATE</label><input id="lockerEnd" type="date" value="${esc(cur?.end_date||'')}"></div></div><div class="modalfoot"><button class="btn" onclick="closeModal()">Cancel</button>${cur?`<button class="btn" onclick="releaseLocker(${Number(id)})">Release</button>`:''}<button class="btn primary" onclick="saveLocker(${Number(id||0)})">Save Locker</button></div></div></div></div>`}
async function saveLocker(id){const locker=document.getElementById('lockerNo').value.trim(),member=document.getElementById('lockerMember').value.trim();if(!locker||!member)return toast('Locker number and member are required.');const fd=new FormData();fd.append('locker_no',locker);fd.append('member_id',member);fd.append('start_date',document.getElementById('lockerStart').value);fd.append('end_date',document.getElementById('lockerEnd').value);if(id)fd.append('id',id);try{const r=await fetch('admin_api.php?action=assign_locker',{method:'POST',body:fd,credentials:'same-origin'});const d=await r.json();if(!r.ok||d.success===false)throw Error(d.message||'Could not save locker');closeModal();toast(d.message||'Locker saved');load()}catch(e){toast(e.message)}}
async function releaseLocker(id){if(!confirm('Release this locker?'))return;try{const r=await fetch('admin_api.php?action=release_locker',{method:'POST',body:new URLSearchParams({id:String(id)}),credentials:'same-origin'});const d=await r.json();if(!r.ok||d.success===false)throw Error(d.message||'Could not release locker');closeModal();toast(d.message||'Locker released');load()}catch(e){toast(e.message)}}
load();
</script></body></html>
